package cadastro.pessoas.exception;

public class RecursoNaoEncontradoException extends RuntimeException {
    public RecursoNaoEncontradoException() {
        super("Pessoa n√£o encontrada");
    }

    public RecursoNaoEncontradoException(String mensagem) {
        super(mensagem);
    }
}
